# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca751d1455a3c4e9c035ed7d31c2cbeca2e97b8a4f3a54593e2ded8a404a1537eb97cb6081e6b65646dc97cf4adab7885ae0c2d097d914a47dde6dcc9fca9be0

test:
  secret_key_base: 11c1ffe73e549c7f5acec0d191ba022fd6b7361d47199a11b3057d03354b673fb35d1728d0ecc26a28248182ceee78e6e62368bccc5b7cf0134653261442e5e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
